### ISSUE TITLE
32 bit version of WireguardUI

### ISSUE THREAD

**Issue by cjbaghl** [bmcgonag/Vector-Client#4]
Vector-Client works great on a 64 bit system.  Sadly, I have a 32 bit system on which I would like to runt the Vector-Client. I suspect this needs to be supported by netralino.js.  Their website indicated support for 32 bit Windows, but not sure about Linux.

**Comment by bmcgonag** [comment]
@cjbaghl  I looked into this a bit, and you are correct.  It appears 32 bit is not supported on linux for NeutralinoJS.  I'll keep an eye on it though.  I'd like to use it on R-Pi's too, but haven't messed with it yet.

**Comment by cjbaghl** [comment]
Brian,

Thank you for looking into this for me.  It's no big deal.  The Vector
client made it convenient.
This is very much an edge case since 32 bit is quickly fading away.

I truly appreciate all you do for the open source community!
I absolutely love your Awesome Open Source Youtube channel.  You take a lot
of care making sure the concepts are clearly explained and you provide
greate, concrete examples.  Please continue.

Kind regards,
Carl Luersen
