### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by jotrocken** [bmcgonag/Vector-Client#5]
I used WireguardUI on my Linux client (Ubuntu) and installed it with wgvpn.sh.
Now I want to uninstall but don't know how to? Is there any uninstall script instead of using `apt-get purge`?

**Comment by skaox** [comment]
Just delete /opt/WiregUIrd

sudo rm -R /opt/WiregUIrd

**Comment by bmcgonag** [comment]
@skaox is correct.
